[package]
name = "lab1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plotters="0.3.1"
nohash-hasher="0.2.0"
gtk = { version = "0.2", package = "gtk4" }
tempdir="0.3.7"
