[package]
name = "lab1"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.0.0"
nalgebra = "0.29.0"
glium = "0.30.2"
sdl2 = "0.34.2"
